### ISSUE TITLE
main.py not available?

### ISSUE THREAD

**Issue by jdubkim** [stanford-cs336/spring2024-lectures#1]
Hi thank you so much for releasing this amazing contents! But it seems like main.py is deleted during some of the previous commits. Is there a reason why it's deleted? Thank you!

Commit: https://github.com/stanford-cs336/spring2024-lectures/commit/a4470ad4a91b221e4c09465ce891e2e65ec11627#diff-b10564ab7d2c520cdd0243874879fb0a782862c3c902ab535faabe57d5a505e1

**Comment by jdubkim** [comment]
Is it deleted because running each python file (lecture01.py, lecture02.py) individually is more convenient?

**Comment by percyliang** [comment]
Yes, you just run each lecture file individually.
